const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const KEY='qm_pro_v6_state';let type='payment';
const today=()=>new Date().toISOString().slice(0,10);const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(n)||0);const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[m]));
const defaults={settings:{name:'SHANGRILAS BEACH RESORT',address:'Vijay Nagar, Swaraj Dweep, South Andaman - 744211, A & N Islands',phone:'9474252529',email:'shangrilasbeachresort@gmail.com',website:'www.shangrilasbeachresort.in',account:'Shangrilas Beach Resort',upi:'shangrilas@upi',bank:'HDFC Bank',branch:'',ac:'',ifsc:'',banner:'',signature:''},quotes:[]};
function loadState(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return {...defaults,...x,settings:{...defaults.settings,...(x.settings||{})}}}catch{return defaults}}
let state=loadState();
const fields=['guest','agency','phone','email','quoteRef','bookingRef','checkin','checkout','room','occupancy','paymentDate','paymentAmount','paymentMode','transaction','paymentNote','balance','message'];
function lastQuote(){return state.draft||state.quotes?.[0]||null}
function loadFromQuote(q){if(!q)return;$('#guest').value=q.guest||'';$('#agency').value=q.agency||'';$('#phone').value=q.phone||'';$('#email').value=q.email||'';$('#quoteRef').value=q.ref||'';$('#bookingRef').value=q.ref||'';$('#checkin').value=q.checkin||today();$('#checkout').value=q.checkout||'';$('#room').value=(q.items||[]).map(i=>`${i.name} × ${i.qty} room(s)`).join(', ');$('#occupancy').value=`${q.adults||0} Adults, ${q.children||0} Children`;$('#balance').value='0';$('#message').value= type==='payment'?'We confirm receipt of the payment mentioned above. Thank you for your payment.':'Your booking is confirmed. We look forward to welcoming you to our resort.';render()}
function defaultsForm(){const q=lastQuote();if(q){loadFromQuote(q)}else{fields.forEach(k=>{const e=$('#'+k);if(e)e.value=''});$('#paymentDate').value=today();$('#checkin').value=today();$('#paymentMode').value='UPI';$('#message').value=type==='payment'?'We confirm receipt of the payment mentioned above. Thank you for your payment.':'Your booking is confirmed. We look forward to welcoming you to our resort.'}render()}
function data(){const d={};fields.forEach(k=>d[k]=$('#'+k)?.value||'');return d}
function quoteSummary(d){const s=state.settings;return `<div class="sheet"><div class="qtop"><div><div class="brandtitle">${esc(s.name)}</div><div class="small">${esc(s.address)}</div><div class="small">Phone: <span class="no-link">${esc(s.phone)}</span> &nbsp;|&nbsp; Email: <span class="no-link">${esc(s.email)}</span></div><div class="small">${s.gstin?`GSTIN: ${esc(s.gstin)}`:''}</div><div class="orange-line"></div></div><div class="refbox"><strong>${type==='payment'?'PAYMENT RECEIPT':'BOOKING CONFIRMATION'}</strong><span class="badge">${type==='payment'?'PAYMENT RECEIVED':'BOOKING CONFIRMED'}</span><br>Ref: ${esc(d.bookingRef||d.quoteRef||'—')}<br>Date: ${esc(d.paymentDate||today())}</div></div><div class="grid2"><div class="box"><div class="boxtitle">PREPARED FOR</div><div class="body"><b>${esc(d.guest||'—')}</b><br>Phone: <span class="no-link">${esc(d.phone||'—')}</span><br>Email: <span class="no-link">${esc(d.email||'—')}</span><br>Agency: ${esc(d.agency||'—')}</div></div><div class="box"><div class="boxtitle">STAY DETAILS</div><div class="body">Check-in: <b>${esc(d.checkin||'—')}</b><br>Check-out: <b>${esc(d.checkout||'—')}</b><br>Occupancy: ${esc(d.occupancy||'—')}<br>Room / Stay: ${esc(d.room||'—')}</div></div></div><div class="highlight"><div class="label">${type==='payment'?'PAYMENT RECEIVED':'BOOKING CONFIRMED'}</div><div class="big">${type==='payment'?money(d.paymentAmount):'Your reservation is confirmed'}</div>${type==='payment'?`<div class="small">Payment Mode: ${esc(d.paymentMode||'—')} &nbsp; | &nbsp; Transaction / UTR: ${esc(d.transaction||'—')}</div>`:`<div class="small">Quotation Ref: ${esc(d.quoteRef||'—')} &nbsp; | &nbsp; Booking Ref: ${esc(d.bookingRef||'—')}</div>`}</div><div class="rows"><div class="row"><span>${type==='payment'?'Payment Date':'Confirmation Date'}</span><strong>${esc(d.paymentDate||today())}</strong></div><div class="row"><span>Payment Mode</span><strong>${esc(d.paymentMode||'—')}</strong></div><div class="row"><span>${type==='payment'?'Balance Due':'Balance Payable'}</span><strong>${money(d.balance)}</strong></div>${d.paymentNote?`<div class="row"><span>Note</span><strong>${esc(d.paymentNote)}</strong></div>`:''}</div>${s.banner?`<img class="banner" src="${s.banner}" alt="Promo Banner">`:''}<div class="message">${esc(d.message||'')}</div>${s.signature?`<img class="signature" src="${s.signature}" alt="Authorized Signature">`:''}<div class="footer">Thank you for choosing ${esc(s.name)}<br>Phone: <span class="no-link">${esc(s.phone)}</span> &nbsp;|&nbsp; Email: <span class="no-link">${esc(s.email)}</span> &nbsp;|&nbsp; <span class="no-link">${esc(s.website)}</span></div></div>`}
function render(){const d=data();$('#document').innerHTML=quoteSummary(d)}
function htmlForEmail(){const d=data();return `<!doctype html><html><body style="margin:0;background:#fff;font-family:Arial,sans-serif;color:#111827">${quoteSummary(d).replace('<div class="sheet">','<div style="width:760px;max-width:100%;margin:0 auto;background:#fff;border:1px solid #bfc8d5;padding:20px">').replace('</div>','</div>')}</body></html>`}
async function copyEmail(){const html=htmlForEmail();try{await navigator.clipboard.write([new ClipboardItem({'text/html':new Blob([html],{type:'text/html'}),'text/plain':new Blob([document.querySelector('#document').innerText],{type:'text/plain'})})])}catch{const ta=document.createElement('textarea');ta.value=html;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}alert('Template copied. Paste it into Gmail/Outlook.')}
function setType(next){type=next;$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.template===type));$('#formTitle').textContent=type==='payment'?'Payment Received':'Booking Confirmed';defaultsForm()}
$$('.tab').forEach(b=>b.onclick=()=>setType(b.dataset.template));fields.forEach(k=>$('#'+k)?.addEventListener('input',render));$('#loadLast').onclick=()=>loadFromQuote(lastQuote());$('#copyEmail').onclick=copyEmail;$('#print').onclick=()=>window.print();$('#reset').onclick=defaultsForm;defaultsForm();
